import type { Request } from "@/store/requests-provider"

// Mock data for Almaty, Kazakhstan
export const mockRequests: Request[] = [
  {
    id: "1",
    title: "Не работает лифт",
    description: "В подъезде №3 не работает лифт уже 2 дня. Застревает между этажами.",
    category: "lift",
    status: "in_progress",
    coordinates: [43.238293, 76.889709],
    address: "мкр. Самал-2, дом 111",
    author: "Жилец",
    iin: "950101300123",
    city: "Алматы",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Авария водоснабжения",
    description: "Прорвало трубу в подвале, вода затапливает первый этаж.",
    category: "emergency",
    status: "new",
    coordinates: [43.222015, 76.85125],
    address: "ул. Розыбакиева, дом 247",
    author: "Жилец",
    iin: "880515400234",
    city: "Алматы",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "Не убран двор",
    description: "После снегопада двор не убирается уже 5 дней.",
    category: "cleaning",
    status: "new",
    coordinates: [43.236525, 76.945465],
    address: "мкр. Аксай-4, дом 89",
    author: "Жилец",
    iin: "920320500345",
    city: "Алматы",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "Не работает освещение",
    description: "В подъезде погас свет на всех этажах.",
    category: "lighting",
    status: "done",
    coordinates: [43.25097, 76.92807],
    address: "мкр. Мамыр-1, дом 29",
    author: "Жилец",
    iin: "930430600456",
    city: "Алматы",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "5",
    title: "Сломана дверь подъезда",
    description: "Входная дверь не закрывается, замок сломан.",
    category: "repair",
    status: "new",
    coordinates: [43.21068, 76.867041],
    address: "ул. Масанчи, дом 98б",
    author: "Жилец",
    iin: "940525700567",
    city: "Алматы",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "6",
    title: "Протекает крыша",
    description: "На последнем этаже протекает крыша, вода капает в квартиру.",
    category: "emergency",
    status: "in_progress",
    coordinates: [43.26529, 76.942947],
    address: "мкр. Алатау, дом 12",
    author: "Жилец",
    iin: "960616800678",
    city: "Алматы",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "7",
    title: "Мусор не вывозится",
    description: "Мусорные баки переполнены, вывоз не осуществляется.",
    category: "cleaning",
    status: "new",
    coordinates: [43.21875, 76.89216],
    address: "мкр. Жетысу-2, дом 45",
    author: "Жилец",
    iin: "970717900789",
    city: "Алматы",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "8",
    title: "Разбитые окна в подъезде",
    description: "На 2-м этаже разбиты окна, дует холодный воздух.",
    category: "repair",
    status: "in_progress",
    coordinates: [43.24268, 76.90482],
    address: "мкр. Самал-3, дом 56",
    author: "Жилец",
    iin: "980818000890",
    city: "Алматы",
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "9",
    title: "Не работает домофон",
    description: "Домофон не отвечает на звонки.",
    category: "repair",
    status: "new",
    coordinates: [43.23002, 76.91555],
    address: "мкр. Достык, дом 138",
    author: "Жилец",
    iin: "990919100901",
    city: "Алматы",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "10",
    title: "Отопление слабое",
    description: "В квартирах холодно, батареи едва теплые.",
    category: "heating",
    status: "in_progress",
    coordinates: [43.25432, 76.88015],
    address: "ул. Толе би, дом 291",
    author: "Жилец",
    iin: "001020201012",
    city: "Алматы",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "11",
    title: "Парковка заблокирована",
    description: "Чужие машины заняли все парковочные места.",
    category: "parking",
    status: "new",
    coordinates: [43.22547, 76.92538],
    address: "мкр. Навои, дом 37",
    author: "Жилец",
    iin: "011130301123",
    city: "Алматы",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "12",
    title: "Шум от ремонта",
    description: "Соседи делают ремонт в неположенное время, очень шумно.",
    category: "noise",
    status: "done",
    coordinates: [43.26015, 76.95567],
    address: "мкр. Алмагуль, дом 5",
    author: "Жилец",
    iin: "021240402234",
    city: "Алматы",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "13",
    title: "Детская площадка сломана",
    description: "Качели и горка на детской площадке сломаны и опасны.",
    category: "playground",
    status: "new",
    coordinates: [43.24821, 76.89843],
    address: "мкр. Орбита-1, дом 22",
    author: "Жилец",
    iin: "031350503345",
    city: "Алматы",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "14",
    title: "Граффити на стенах",
    description: "На стенах подъезда появились граффити.",
    category: "cleaning",
    status: "new",
    coordinates: [43.21687, 76.93621],
    address: "мкр. Жулдыз-1, дом 8",
    author: "Жилец",
    iin: "041460604456",
    city: "Алматы",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "15",
    title: "Запах газа",
    description: "В подъезде чувствуется запах газа, требуется проверка.",
    category: "emergency",
    status: "in_progress",
    coordinates: [43.23341, 76.87395],
    address: "ул. Байтурсынова, дом 156",
    author: "Жилец",
    iin: "051570705567",
    city: "Алматы",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  // Pavlodar mock requests (KSK reports included)
  {
    id: "p1",
    title: "Провал асфальта у подъезда",
    description: "Образовался провал асфальта рядом с входом, опасно для машин и пешеходов.",
    category: "repair",
    status: "done",
    coordinates: [52.2860, 76.9540],
    address: "ул. Абая, дом 12",
    author: "Жилец Павлодар",
    iin: "860101300123",
    city: "Павлодар",
    report: "Дефект устранён: асфальт отсыпан и уплотнён, установлены предупреждающие знаки.",
    reportPhotos: [
      "https://picsum.photos/id/1018/400/300",
      "https://picsum.photos/id/1025/400/300",
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "p2",
    title: "Не работает освещение на парковке",
    description: "Фонари не горят уже неделю, темно и небезопасно.",
    category: "lighting",
    status: "done",
    coordinates: [52.2835, 76.9621],
    address: "пр. Назарбаева, 44",
    author: "Жилец Павлодар",
    iin: "870202400234",
    city: "Павлодар",
    report: "Освещение восстановлено: заменили лампы и проверили электрику.",
    reportPhotos: [
      "https://picsum.photos/id/1035/400/300",
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "p3",
    title: "Затопление подвального помещения",
    description: "Во время дождя вода попадает в подвальное помещение, требуется обследование и устранение.",
    category: "emergency",
    status: "in_progress",
    coordinates: [52.2921, 76.9487],
    address: "ул. Казыбек би, 7",
    author: "Жилец Павлодар",
    iin: "880303500345",
    city: "Павлодар",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
]
